#!/usr/bin/env ruby
dir = File.join(File.dirname(File.realdirpath(__FILE__)), '..')

if RUBY_VERSION < '1.9.2'
  $stderr.puts 'your ruby is too old!'
  exit 1
end

$LOAD_PATH.unshift File.join(dir, 'lib')

ENV['BUNDLE_GEMFILE'] ||= File.join(dir, 'Gemfile')

require 'pltt'
require 'bundler/setup'
require 'pltt/runner'
