#!/usr/bin/env ruby
dir = File.join(File.dirname(File.realdirpath(__FILE__)), '..')

if RUBY_VERSION < '1.9.2'
  $stderr.puts 'your ruby is too old!'
  exit 1
end

$LOAD_PATH.unshift File.join(dir, 'lib')

# ENV['BUNDLE_GEMFILE'] ||= File.join(dir, 'Gemfile')

require 'bundler/inline'
gemfile do
  source 'https://rubygems.org'
  gem 'git', '~> 1.5.0', require: false
  gem 'gitlab', '~> 4.4.0', require: false
  gem 'hashids', require: false
  gem 'oj', require: false
  gem 'rake', require: false
  gem 'stringex', require: false
  gem 'terminal-table', '>= 1.8.0', require: false
  gem 'thor', require: false
  gem 'tty-prompt', require: false
end
require 'pltt'
#require 'bundler/setup'
require 'pltt/runner'
